### ISSUE TITLE
Update code for rails 4 compatibility and above

### ISSUE THREAD

**Issue by cyberteksys** [midwire/my_zipcode_gem#12]
Running `rake zipcodes:update` gives the following error in rails 4.2.5:

`NoMethodError: undefined method 'attr_accessible' for State (call 'State.connection' to establish a connection):Class`

due to strong params. Temporary fix is by using the protected_attributes gem. Also, please update scope syntax in county.rb so the update completes.

```ruby
scope :without_zipcodes, -> { joins("LEFT JOIN zipcodes ON zipcodes.county_id = counties.id").where("zipcodes.county_id IS NULL") }
scope :without_state, -> { where("state_id IS NULL") }
```

Thanks!

**Comment by midwire** [comment]
Thanks @cyberteksys . We would welcome a PR if you have the time.

**Comment by cmckni3** [comment]
@midwire Do we want to support Rails < 4?

**Comment by midwire** [comment]
@cmckni3 I'd rather not, but they were using `4.2.5` above.

**Comment by cmckni3** [comment]
Ok, I was just wondering about the versioning scheme. Should probably state that version 0.1.x is for Rails < 4

**Comment by midwire** [comment]
should we create tag/branch for that? we could tag it and then announce we won't support that going forward in the readme.

**Comment by cmckni3** [comment]
They are already tagged. Announcing in the readme sounds good to me.

**Comment by midwire** [comment]
Thanks Chris. I plan to get more familiar with this project again. I'll update the README today as well.

**Comment by cmckni3** [comment]
@cyberteksys good in master

@midwire can you cut a new Rubygems release?

**Comment by cyberteksys** [comment]
thanks @cmckni3 and @midwire

**Comment by cmckni3** [comment]
No problem @cyberteksys

**Comment by midwire** [comment]
Confirmed. 0.2.1 is live on rubygems.org. https://rubygems.org/gems/my_zipcode_gem
