### ISSUE TITLE
rake zipcodes:update 404 error

### ISSUE THREAD

**Issue by jump3r34** [midwire/my_zipcode_gem#18]
In the rake tasks - update throws a 404 error and I can only assume it is because the "https://github.com/midwire/free_zipcode_data/raw/master/all_us_states.csv" is throwing a 404 error.

I am just looking for the best option to get the data into the newly created tables.

**Comment by cblackburn-ajla** [comment]
My apologies. I have reworked that project and forgotten that the gem depends on those files. I'll add them back right now.

**Comment by jump3r34** [comment]
Man! You are on top of your game!

Quickest response in github history!

**Comment by cblackburn-ajla** [comment]
Restored. Again, sorry about that. I'll update the gem to use the newer data as soon as I can get to it.  Let us know if any other issues.

**Comment by jump3r34** [comment]
I have to be honest - if this were a for-profit - I would post this conversation on facebook to show how quick you are and make you more $$$, hopefully.  I have already told 4 or 5 programmers in the last 5 mins how quick you responded.

Thanks!
