### ISSUE TITLE
New Rubygems release

### ISSUE THREAD

**Issue by cmckni3** [midwire/my_zipcode_gem#22]

**Comment by cmckni3** [comment]
Maybe we could use Travis CI for automatically releasing the gem?

**Comment by cblackburn-ajla** [comment]
I didn't know Travis would do that. I don't mind configuring access for you to do it directly either.  Checking into that now.

**Comment by cblackburn-ajla** [comment]
Update: @cmckni3 you are an owner there on Rubygems.org. You should be able to push a new version of the gem. I think I set it up with a rake task from my midwire_common gem that will let you just do `rake release` or something like that. Let me know if you have trouble.  Also, if you can figure out how to make Travis CI do it that's certainly fine by me.

**Comment by cmckni3** [comment]
Awesome, I will check when I have a chance. As long as we're cautious about merging to master and eventually fix the tests, I'm fine with Travis CI releasing a new gem. I think dpl handles it but would need to bump the version through a rake task or the ruby gems helper.

**Comment by cmckni3** [comment]
```
You do not have permission to push to this gem. Ask an owner to add you with: gem owner my_zipcode_gem --add cmckni3@gmail.com
```

**Comment by cmckni3** [comment]
Get that error when trying to push @midwire. I didn't see it in my dashboard but I tried doing a release anyways.

**Comment by cmckni3** [comment]
Getting an error message on Travis CI that it's inactive and I don't have access to enable it. The build from master ran a few minutes ago though.

**Comment by midwire** [comment]
@cmckni3 I did this: `gem owner my_zipcode_gem --add cmckni3@gmail.com` and it now lists you as an owner.  Working on the travis thing now.

**Comment by midwire** [comment]
Our Travis CI job is now enabled again. I don’t remember disabling it but apparently I did 6 years ago. Hard to believe we’ve been maintaining it for that long. :) ping me if any other issues.

**Comment by cmckni3** [comment]
I see both changes now. Thanks! 👍

**Comment by cmckni3** [comment]
0.2.2 has been pushed to Rubygems
