### ISSUE TITLE
missing zipcodes

### ISSUE THREAD

**Issue by woahstorkdork** [midwire/my_zipcode_gem#26]
Currently using this gem for a delivery wizard of sorts, thanks for your work on this!

Was just running an import script for active delivery zipcodes and ran into a few hiccups due to the gem missing some zipcodes.
Here are the missing codes I've found thus far:

```
{
	city: "Bradbury",
	lat: 34.154308,
	lon:	-117.968588,
	code: "91008",
	county_id: 1712,
	state_id: 5,
	area_code: "626"
},
{
	city: "Carlsbad",
	lat: 33.155588,
	lon:	-117.279445,
	code: "92010",
	county_id: 2525,
	state_id: 5,
	area_code: "760"
},
{
	city: "Fairfield",
	lat: 38.225028,
	lon:	-122.124457,
	code: "94534",
	county_id: 2525,
	state_id: 5,
	area_code: "707"
},
{
	city: "Sacramento",
	lat:	38.583952,
	lon:	-121.491028,
	code: "95811",
	county_id: 2483,
	state_id: 5,
	area_code: "916"
}
```

**Comment by cmckni3** [comment]
The data comes from https://github.com/midwire/free_zipcode_data/raw/master/all_us_states.csv

Will look into running the script in that repo to look for updated data.

**Comment by midwire** [comment]
@woahstorkdork thanks for this report. Unfortunately @cmckni3 is correct. We source the data from geonames, through the `free_zipcode_data` project. Any errors or omissions will hopefully be corrected by them in due course. If you find any additional problems please let us know. We may need to find a different source of data. Closing this for now.

**Comment by midwire** [comment]
@woahstorkdork thanks for this report. Unfortunately @cmckni3 is correct. We source the data from geonames, through the `free_zipcode_data` project. Any errors or omissions will hopefully be corrected by them in due course. If you find any additional problems please let us know. We may need to find a different source of data. Closing this for now.
