### ISSUE TITLE
Release new gem to rubygems

### ISSUE THREAD

**Issue by cmckni3** [midwire/my_zipcode_gem#6]
I'm not an owner on rubygems.org.

[my profile](https://rubygems.org/profiles/cmckni3)

/ping @midwire

**Comment by cmckni3** [comment]
Can I have access to manage webhooks and services as well?

**Comment by midwire** [comment]
Looking in settings, I don't see a way to do that unless I transfer the project to you. You want me to push a new version to rubygems?

**Comment by cmckni3** [comment]
> Looking in settings, I don't see a way to do that unless I transfer the project to you.

Hmm, it would have to be moved to a GitHub organization.

> You want me to push a new version to rubygems?

Yep, it has been awhile since the gem was pushed to rubygems.

**Comment by midwire** [comment]
Version bumped, gem released and I added you to free_zipcode_data in case you want to update the data: https://github.com/midwire/free_zipcode_data

**Comment by cmckni3** [comment]
Awesome. Thanks!
