### ISSUE TITLE
Argument Error in Rails Generator for Creating Migration File

### ISSUE THREAD

**Issue by Jbur43** [midwire/my_zipcode_gem#9]
```
Running via Spring preloader in process 8766
     gemfile  mocha
      create  app/models/zipcode.rb
      create  app/models/county.rb
      create  app/models/state.rb
/Users/myusername/.rvm/gems/ruby-2.3.0/gems/my_zipcode_gem-0.1.4/lib/generators/my_zipcode_gem/models_generator.rb:35:in `create_migration': wrong number of arguments (given 3, expected 0) (ArgumentError)
```

I am getting this argument error when the generator tries to create the migration file. Do you have an idea what arguments could be being passed into the file that aren't supposed to be there?

**Comment by cmckni3** [comment]
My guess is that arguments for `create_migration` changed in Rails.

Which version of Rails are you using?

**Comment by ryskin** [comment]
Same problem

**Comment by safetymonkey** [comment]
I'm having the same problem running Rails 4.2.6.

**Comment by stephwag** [comment]
Same here running Rails 4.2.5 and Ruby 2.3.3

**Comment by cmckni3** [comment]
Working on reproducing it

**Comment by cmckni3** [comment]
This has been fixed in master. @midwire can you release a new version of the gem to Rubygems?

**Comment by midwire** [comment]
Yes. I'll do that today, ASAP.

**Comment by midwire** [comment]
Version `0.2.0` is now live: https://rubygems.org/gems/my_zipcode_gem. Thanks to everyone who helped. For some reason I've not been getting Github emails for some time.
